// 69 Wilayas d'Algerie — novembre 2025
// 48 historiques + 10 (2021) + 11 (2025)

export const WILAYAS = [
  // 48 wilayas historiques
  'Adrar',
  'Chlef',
  'Laghouat',
  'Oum El Bouaghi',
  'Batna',
  'Bejaia',
  'Biskra',
  'Bechar',
  'Blida',
  'Bouira',
  'Tamanrasset',
  'Tebessa',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Alger',
  'Djelfa',
  'Jijel',
  'Setif',
  'Saida',
  'Skikda',
  'Sidi Bel Abbes',
  'Annaba',
  'Guelma',
  'Constantine',
  'Medea',
  'Mostaganem',
  "M'Sila",
  'Mascara',
  'Ouargla',
  'Oran',
  'El Bayadh',
  'Illizi',
  'Bordj Bou Arreridj',
  'Boumerdes',
  'El Tarf',
  'Tindouf',
  'Tissemsilt',
  'El Oued',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'Ain Defla',
  'Naama',
  'Ain Temouchent',
  'Ghardaia',
  'Relizane',
  // 10 wilayas creees en 2021 (Sud)
  'Timimoune',
  'Bordj Badji Mokhtar',
  'Ouled Djellal',
  'Beni Abbes',
  'In Salah',
  'In Guezzam',
  'Touggourt',
  'Djanet',
  "El M'Ghair",
  'El Menia',
  // 11 wilayas creees en novembre 2025 (Hauts-Plateaux/Sud)
  'Aflou',
  'Barika',
  'Ksar Chellala',
  'Messaad',
  'Ain Oussera',
  'Boussaada',
  'El Abiodh Sidi Cheikh',
  'El Kantara',
  'Bir El Ater',
  'Ksar El Boukhari',
  'El Aricha',
]

export const LISTING_TYPES = [
  { value: 'appartement', label: 'Appartement' },
  { value: 'villa',       label: 'Villa / Maison' },
  { value: 'studio',      label: 'Studio' },
  { value: 'terrain',     label: 'Terrain' },
  { value: 'local',       label: 'Local commercial' },
  { value: 'bureau',      label: 'Bureau' },
]

export const TRANSACTION_TYPES = [
  { value: 'vente',    label: 'A vendre' },
  { value: 'location', label: 'A louer' },
]
